name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
          tags: mura:latest

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{secrets.GOOGLE_CREDENTIALS_JSON}}"

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker africa-south1-docker.pkg.dev

      - name: Build and push Docker image to Artifact Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: africa-south1-docker.pkg.dev/regal-timing-437806-e7/cloud-run-source-deploy/mura:latest
          build-args: |
            HTTP_PORT=8080

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{secrets.GOOGLE_CREDENTIALS_JSON}}"

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: africa-south1-docker.pkg.dev/regal-timing-437806-e7/cloud-run-source-deploy/mura:latest
          service: mura
          region: africa-south1
          env_vars: |
            GEMINI_API_KEY=${{secrets.GEMINI_API_KEY}}
            GOOGLE_SERVICE_KEY=${{secrets.GOOGLE_SERVICE_KEY}}
            CLOUDINARY_URL=${{secrets.CLOUDINARY_URL}}
            RUN_ENV=cloudrun
          timeout: 150s
