name: CI/CD Pipeline

on:
  push:
    branches:
      - prod
    pull_request:
      branches:
        - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v1

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.22"

      # Step 3: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      # Step 4: Set up Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}

      # Step 5: Run tests
      - name: Run tests
        run: go test ./...

      # Step 6: Initialize App Engine (if not already initialized)
      - name: Initialize App Engine (if not already initialized)
        run: |
          if ! gcloud app describe > /dev/null 2>&1; then
            gcloud app create --region=us-central1
          fi

      # Step 7: Deploy application
      - name: Deploy application
        run: |
          echo "Deploying application"
          gcloud app deploy --quiet
